// swift-tools-version: 5.9
// Generated by scripts/distribution.py. Do not edit release checksums by hand.
import PackageDescription

let package = Package(
    name: "WebP-Cocoa",
    platforms: [
        .macOS("11.0"), .iOS("15.0"),
        .tvOS("15.0"), .watchOS("8.0"),
        .visionOS("1.0")
    ],
    products: [
        .library(name: "WebP", targets: ["WebP"]),
        .library(name: "WebPDecoder", targets: ["WebPDecoder"]),
        .library(name: "WebPDemux", targets: ["WebPDemux"]),
        .library(name: "WebPMux", targets: ["WebPMux"]),
        .library(name: "WebPDecoding", targets: ["WebPDecoder", "WebPDemux"]),
        .library(name: "WebPFull", targets: ["WebP", "WebPDemux", "WebPMux"]),
    ],
    targets: [
        .binaryTarget(name: "WebP", path: "dist/WebP.xcframework"),
        .binaryTarget(name: "WebPDecoder", path: "dist/WebPDecoder.xcframework"),
        .binaryTarget(name: "WebPDemux", path: "dist/WebPDemux.xcframework"),
        .binaryTarget(name: "WebPMux", path: "dist/WebPMux.xcframework"),
    ]
)
