#!/usr/bin/env python3
"""Create verifiable GitHub Release assets and SwiftPM binary manifests.

The source checkout uses local paths. Only a release commit gets remote URLs,
after the ZIP bytes exist and their real SwiftPM checksums have been computed.
"""
import argparse
import hashlib
import json
import plistlib
import re
import shutil
import tempfile
import zipfile
from pathlib import Path

from config import DIST, LOCK, PRODUCTS, ROOT, SLICES

REPOSITORY = "TimOliver/WebP-Cocoa"
CONVENIENCE_PRODUCTS = {
    "WebPImageIO": ["WebPDecoder", "WebPDemux"],
    "WebPFull": ["WebP", "WebPDemux", "WebPMux"],
}


def sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def validate_tag(tag):
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", tag):
        raise ValueError("Use a plain SemVer tag, for example 1.6.0")
    if tag != LOCK["libwebp"]["version"]:
        raise ValueError(f"Tag {tag} differs from pinned libwebp {LOCK['libwebp']['version']}")
    return tag


def validate_repository(repository):
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("Repository must be a GitHub owner/name")
    return repository


def manifest(*, local=False, tag=None, checksums=None, repository=REPOSITORY):
    """Return a manifest; remote entries always require actual ZIP checksums."""
    if not local:
        validate_tag(tag or "")
        validate_repository(repository)
        if set(checksums or {}) != set(PRODUCTS):
            raise ValueError("A SHA-256 checksum is required for every binary target")
    products = {name: [name] for name in PRODUCTS} | CONVENIENCE_PRODUCTS
    lines = [
        "// swift-tools-version: 5.9",
        "// Generated by scripts/distribution.py. Do not edit release checksums by hand.",
        "import PackageDescription", "", "let package = Package(",
        '    name: "WebP-Cocoa",',
        "    platforms: [",
        f'        .macOS("{LOCK["deployment"]["macos"]}"), .iOS("{LOCK["deployment"]["ios"]}"),',
        f'        .tvOS("{LOCK["deployment"]["tvos"]}"), .watchOS("{LOCK["deployment"]["watchos"]}"),',
        f'        .visionOS("{LOCK["deployment"]["visionos"]}")',
        "    ],", "    products: [",
    ]
    for name, targets in products.items():
        lines.append(f'        .library(name: "{name}", targets: {json.dumps(targets)}),')
    lines.extend(["    ],", "    targets: ["])
    for name in PRODUCTS:
        if local:
            lines.append(f'        .binaryTarget(name: "{name}", path: "dist/{name}.xcframework"),')
        else:
            checksum = checksums[name]
            if not re.fullmatch(r"[0-9a-f]{64}", checksum):
                raise ValueError(f"Invalid SHA-256 checksum for {name}")
            url = f"https://github.com/{repository}/releases/download/{tag}/{name}.xcframework.zip"
            lines.extend([
                f'        .binaryTarget(name: "{name}",',
                f'                      url: "{url}",',
                f'                      checksum: "{checksum}"),',
            ])
    lines.extend(["    ]", ")", ""])
    return "\n".join(lines)


def validate_xcframework(path):
    name = path.name.removesuffix(".xcframework")
    if name not in PRODUCTS:
        raise ValueError(f"Unknown XCFramework product: {path.name}")
    with (path / "Info.plist").open("rb") as stream:
        info = plistlib.load(stream)
    expected = {
        (spec["platform"], spec.get("variant", ""), tuple(sorted(spec["archs"])))
        for spec in SLICES.values()
    }
    libraries = info.get("AvailableLibraries", [])
    actual = {
        (entry["SupportedPlatform"], entry.get("SupportedPlatformVariant", ""),
         tuple(sorted(entry["SupportedArchitectures"])))
        for entry in libraries
    }
    if len(libraries) != len(SLICES) or actual != expected:
        raise ValueError(f"{path.name} is incomplete; release packaging requires all {len(SLICES)} slices")
    for entry in libraries:
        for field in ("LibraryIdentifier", "LibraryPath", "HeadersPath"):
            value = Path(entry[field])
            if value.is_absolute() or ".." in value.parts:
                raise ValueError(f"Unsafe {field} in {path.name}")
        library = path / entry["LibraryIdentifier"] / entry["LibraryPath"]
        headers = path / entry["LibraryIdentifier"] / entry["HeadersPath"]
        if library.suffix != ".a" or not library.is_file() or not headers.is_dir():
            raise ValueError(f"Missing static library or headers in {path.name}")
        required_headers = ["module.modulemap", *PRODUCTS[name]["headers"],
                            *(f"webp/{header}" for header in PRODUCTS[name]["headers"])]
        for header in required_headers:
            if not (headers / header).is_file():
                raise ValueError(f"{path.name} is missing {header} in {entry['LibraryIdentifier']}")
    # libwebp's BSD license and patent grant must travel with each binary.
    for required in ("COPYING", "PATENTS", "AUTHORS", "WebP-Cocoa-LICENSE"):
        if not (path / "Licenses" / required).is_file():
            raise ValueError(f"{path.name} is missing license/notice {required}")


def zip_framework(path, output):
    """Stable ordering, timestamps and permissions for repeatable archive bytes."""
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for file in sorted(path.rglob("*")):
            if file.is_symlink():
                raise ValueError(f"Unexpected symlink in static XCFramework: {file}")
            if file.is_file():
                entry = zipfile.ZipInfo(file.relative_to(path.parent).as_posix(), (1980, 1, 1, 0, 0, 0))
                entry.compress_type = zipfile.ZIP_DEFLATED
                entry.create_system = 3
                entry.external_attr = 0o100644 << 16
                archive.writestr(entry, file.read_bytes(), compresslevel=9)


def validate_provenance(provenance):
    if provenance.get("schema") != 1 or provenance.get("libwebp") != LOCK["libwebp"]:
        raise ValueError("build-info.json does not match the pinned libwebp source")
    if provenance.get("toolchain_override") is not False:
        raise ValueError("Development toolchain overrides cannot be released")
    if set(provenance.get("slices", [])) != set(SLICES):
        raise ValueError("build-info.json does not describe every release slice")
    if provenance.get("deployment") != LOCK["deployment"] or set(provenance.get("products", [])) != set(PRODUCTS):
        raise ValueError("build-info.json deployment or products differ from the release contract")
    if provenance.get("architecture_deployment") != LOCK["architecture_deployment"]:
        raise ValueError("build-info.json architecture deployment targets differ from the release contract")
    tools = provenance.get("tools", {})
    for tool, version in LOCK["tools"].items():
        if tool != "sdk" and tools.get(tool) != version:
            raise ValueError(f"build-info.json does not use pinned {tool} {version}")
    sdks = tools.get("sdks", {})
    if tools.get("mismatches") != [] or set(sdks) != {spec["sdk"] for spec in SLICES.values()}:
        raise ValueError("build-info.json toolchain verification is incomplete")
    if any(version != LOCK["tools"]["sdk"] for version in sdks.values()):
        raise ValueError("build-info.json does not use the pinned SDK versions")


def package(tag, repository=REPOSITORY):
    validate_tag(tag)
    validate_repository(repository)
    provenance_path = DIST / "build-info.json"
    provenance = json.loads(provenance_path.read_text())
    validate_provenance(provenance)
    for name in PRODUCTS:
        validate_xcframework(DIST / f"{name}.xcframework")
    output = DIST / "release"
    if output.exists():
        raise ValueError("dist/release already exists; move or remove it before packaging new bytes")
    with tempfile.TemporaryDirectory(prefix="release-", dir=DIST) as staging:
        staging = Path(staging)
        checksums = {}
        for name in PRODUCTS:
            target = staging / f"{name}.xcframework.zip"
            zip_framework(DIST / f"{name}.xcframework", target)
            checksums[name] = sha256(target)
        (staging / "Package.swift").write_text(manifest(tag=tag, checksums=checksums, repository=repository))
        shutil.copy2(provenance_path, staging / "build-info.json")
        shutil.copy2(ROOT / "LICENSE", staging / "LICENSE.WebP-Cocoa")
        sums = "".join(f"{sha256(file)}  {file.name}\n" for file in sorted(staging.iterdir()))
        (staging / "SHA256SUMS").write_text(sums)
        staging.rename(output)
    print(f"Release assets: {output}")
    return output


def verify(directory, tag, repository=REPOSITORY, extract_to=None):
    """Validate downloaded release bytes before allowing draft publication."""
    validate_tag(tag)
    directory = Path(directory)
    entries = {}
    for line in (directory / "SHA256SUMS").read_text().splitlines():
        digest, name = line.split("  ", 1)
        if not re.fullmatch(r"[0-9a-f]{64}", digest) or Path(name).name != name or name in entries:
            raise ValueError("Invalid SHA256SUMS entry")
        if sha256(directory / name) != digest:
            raise ValueError(f"Checksum mismatch: {name}")
        entries[name] = digest
    expected = {f"{name}.xcframework.zip" for name in PRODUCTS} | {"Package.swift", "build-info.json", "LICENSE.WebP-Cocoa"}
    if set(entries) != expected:
        raise ValueError("Unexpected or missing release assets")
    validate_provenance(json.loads((directory / "build-info.json").read_text()))
    checksums = {name: entries[f"{name}.xcframework.zip"] for name in PRODUCTS}
    if (directory / "Package.swift").read_text() != manifest(tag=tag, checksums=checksums, repository=repository):
        raise ValueError("Release Package.swift does not match the downloaded archives")
    if extract_to:
        extract_to = Path(extract_to)
        extract_to.mkdir(parents=True, exist_ok=False)
        dist = extract_to / "dist"
        dist.mkdir()
        for name in PRODUCTS:
            with zipfile.ZipFile(directory / f"{name}.xcframework.zip") as archive:
                for entry in archive.infolist():
                    parts = Path(entry.filename).parts
                    if not parts or parts[0] != f"{name}.xcframework" or ".." in parts or Path(entry.filename).is_absolute():
                        raise ValueError(f"Unsafe archive member: {entry.filename}")
                    if (entry.external_attr >> 16) & 0o170000 == 0o120000:
                        raise ValueError("Release archives must not contain symlinks")
                archive.extractall(dist)
            validate_xcframework(dist / f"{name}.xcframework")
        shutil.copy2(directory / "build-info.json", dist / "build-info.json")
        (extract_to / "Package.swift").write_text(manifest(local=True))
    print(f"Verified release assets: {directory}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    local = commands.add_parser("manifest", help="Generate the source checkout's local binary manifest")
    local.add_argument("--local", action="store_true", required=True)
    local.add_argument("--output", type=Path, default=ROOT / "Package.swift")
    release = commands.add_parser("package", help="Package all slices with real release checksums")
    release.add_argument("--tag", required=True)
    release.add_argument("--repository", default=REPOSITORY)
    check = commands.add_parser("verify", help="Verify downloaded release assets and optionally extract a consumer package")
    check.add_argument("--directory", type=Path, required=True)
    check.add_argument("--tag", required=True)
    check.add_argument("--repository", default=REPOSITORY)
    check.add_argument("--extract-to", type=Path)
    args = parser.parse_args()
    try:
        if args.command == "manifest":
            args.output.write_text(manifest(local=True))
        elif args.command == "package":
            package(args.tag, args.repository)
        else:
            verify(args.directory, args.tag, args.repository, args.extract_to)
    except (ValueError, OSError, KeyError) as error:
        parser.exit(1, f"error: {error}\n")


if __name__ == "__main__":
    main()
